# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RNRecruiterProj' do
    pod 'HyphenateSDK'
    pod 'Masonry'
    pod 'MJExtension'
    pod 'BlocksKit'
    pod 'SDWebImage'
    pod 'Qiniu'
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end
